name: Sistema de Coletores CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sistema_coletores_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d sistema_coletores_test -f database_schema.sql
      env:
        PGPASSWORD: postgres
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sistema_coletores_test
    
    - name: Run linting
      run: |
        flake8 --max-line-length=88 --extend-ignore=E203,W503 *.py

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security checks
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        bandit -r . -x tests/
